# ======================= KAFKA =======================
  zookeeper:
    image: bitnamilegacy/zookeeper:3.7.0
    hostname: zookeeper
    container_name: zookeeper
    env_file:
      - ./kafka/.env
    ports:
      - "2181:2181"
    profiles:
      - kafka
    networks:
      - kafka_network
      - data_network_all

  kafka1:
    image: bitnamilegacy/kafka:2.8.1
    hostname: kafka1
    container_name: kafka1
    env_file:
      - ./kafka/.env
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092,DOCKER://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka1:19092,EXTERNAL://127.0.0.1:9092,DOCKER://host.docker.internal:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_MIN_INSYNC_REPLICAS=1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    profiles:
      - kafka
    networks:
      - kafka_network
      - data_network_all

  kafka2:
    image: bitnamilegacy/kafka:2.8.1
    hostname: kafka2
    container_name: kafka2
    env_file:
      - ./kafka/.env
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:19093,EXTERNAL://0.0.0.0:9093,DOCKER://0.0.0.0:29093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka2:19093,EXTERNAL://127.0.0.1:9093,DOCKER://host.docker.internal:29093
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
      - "29093:29093"
    profiles:
      - kafka
    networks:
      - kafka_network
      - data_network_all

  kafka3:
    image: bitnamilegacy/kafka:2.8.1
    hostname: kafka3
    container_name: kafka3
    env_file:
      - ./kafka/.env
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:19094,EXTERNAL://0.0.0.0:9094,DOCKER://0.0.0.0:29094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka3:19094,EXTERNAL://127.0.0.1:9094,DOCKER://host.docker.internal:29094
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
      - "29094:29094"
    profiles:
      - kafka
    networks:
      - kafka_network
      - data_network_all

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:7.9.4
    hostname: kafka-schema-registry
    container_name: kafka-schema-registry
    env_file:
      - ./kafka/.env
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "8081:8081"
    profiles:
      - kafka
    networks:
      - kafka_network
      - data_network_all

  kafka-connect:
    build: ./kafka/.
    hostname: kafka-connect
    container_name: kafka-connect
    env_file:
      - ./kafka/.env
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - kafka-schema-registry
    ports:
      - "8083:8083"
    profiles:
      - kafka
    networks:
      - kafka_network
      - data_network_all

  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:7.9.4
    hostname: ksqldb-server
    container_name: ksqldb-server
    env_file:
      - ./kafka/.env
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - kafka-schema-registry
    ports:
      - "8088:8088"
    profiles:
      - kafka
    networks:
      - kafka_network
      - data_network_all

  akhq:
    image: tchiotludo/akhq:latest
    container_name: akhq
    hostname: akhq
    env_file:
      - ./kafka/.env
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local-cluster:
              properties:
                bootstrap.servers: "kafka1:19092,kafka2:19093,kafka3:19094"
              schema-registry:
                url: "http://kafka-schema-registry:8081"
              connect:
                - name: "connect-cluster"
                  url: "http://kafka-connect:8083"
              ksql:
                - name: "ksqldb"
                  url: "http://ksqldb-server:8088"
          security:
            default-group: admin
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - kafka-schema-registry
      - kafka-connect
    ports:
      - "9010:8080"
    profiles:
      - kafka
    networks:
      - kafka_network
      - data_network_all

  etl:
    build: ./etl/.
    container_name: etl_kafka
    restart: no
    profiles:
      - kafka
    ports:
      - "8089:8080"
    volumes:
      - ./etl:/home/etl
    stdin_open: true
    tty: true
    entrypoint: ["/bin/sh", "-c"]
    command: tail -f /dev/null
    networks:
      - kafka_network
      - data_network_all

# ==========================postgres===========================

  postgres:
    image: postgis/postgis:latest
    container_name: postgres
    restart: no
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./metabase/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - data_network
      - data_network_all
    command: >
      postgres -c shared_buffers=2GB
              -c work_mem=128MB
              -c maintenance_work_mem=512MB
              -c max_parallel_workers=8
              -c effective_cache_size=6GB
              -c checkpoint_timeout=30min
              -c wal_buffers=16MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  kafka_network:
  data_network_all:
    external: true
